# Generated by Django 5.2.12 on 2026-03-10 19:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_enrollment_and_refactor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradescale',
            options={'ordering': ['-min_percentage'], 'verbose_name': 'Grade Scale', 'verbose_name_plural': 'Grade Scale'},
        ),
        migrations.AlterModelOptions(
            name='semestersubject',
            options={'ordering': ['semester', 'subject__name'], 'verbose_name': 'Semester Subject', 'verbose_name_plural': 'Semester Subjects'},
        ),
        migrations.RenameIndex(
            model_name='enhancedresult',
            new_name='er_status_idx',
            old_name='core_enh_status_idx',
        ),
        migrations.RenameIndex(
            model_name='enrollment',
            new_name='core_enroll_student_0d73b5_idx',
            old_name='enr_class_year_idx',
        ),
        migrations.RenameIndex(
            model_name='enrollment',
            new_name='core_enroll_academi_2c0b7e_idx',
            old_name='enr_year_roll_idx',
        ),
        migrations.RenameIndex(
            model_name='semestersubject',
            new_name='ss_class_sem_year_idx',
            old_name='core_semstr_cls_sem_idx',
        ),
        migrations.AlterField(
            model_name='enhancedresult',
            name='grade',
            field=models.CharField(choices=[('O', 'Outstanding'), ('A+', 'Excellent'), ('A', 'Very Good'), ('B+', 'Good'), ('B', 'Above Average'), ('C', 'Average'), ('F', 'Fail'), ('-', 'Not Graded')], default='-', max_length=3),
        ),
        migrations.AlterField(
            model_name='enhancedresult',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='enhancedresult',
            name='semester_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.semestersubject', verbose_name='Semester Subject'),
        ),
        migrations.AlterField(
            model_name='enhancedresult',
            name='status',
            field=models.CharField(default='Pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='academic_year',
            field=models.CharField(help_text='e.g. 2024-25', max_length=10, verbose_name='Academic Year'),
        ),
        migrations.AlterField(
            model_name='gradescale',
            name='grade',
            field=models.CharField(choices=[('O', 'Outstanding'), ('A+', 'Excellent'), ('A', 'Very Good'), ('B+', 'Good'), ('B', 'Above Average'), ('C', 'Average'), ('F', 'Fail')], max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='gradescale',
            name='grade_points',
            field=models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='gradescale',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gradescale',
            name='is_pass',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='gradescale',
            name='max_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='gradescale',
            name='min_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='notice',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='result',
            name='grade',
            field=models.CharField(choices=[('O', 'Outstanding'), ('A+', 'Excellent'), ('A', 'Very Good'), ('B+', 'Good'), ('B', 'Average'), ('F', 'Fail')], default='F', max_length=3),
        ),
        migrations.AlterField(
            model_name='result',
            name='ia1_marks',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='result',
            name='ia2_marks',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='result',
            name='sem_marks',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AlterField(
            model_name='result',
            name='status',
            field=models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail')], default='Fail', max_length=4),
        ),
        migrations.AlterField(
            model_name='result',
            name='total',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='semestersubject',
            name='academic_year',
            field=models.CharField(help_text='e.g. 2024-25', max_length=10),
        ),
        migrations.AlterField(
            model_name='semestersubject',
            name='credits',
            field=models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='semestersubject',
            name='has_ia',
            field=models.BooleanField(default=True, verbose_name='Has IA'),
        ),
        migrations.AlterField(
            model_name='semestersubject',
            name='has_oral',
            field=models.BooleanField(default=False, verbose_name='Has Oral'),
        ),
        migrations.AlterField(
            model_name='semestersubject',
            name='has_sem',
            field=models.BooleanField(default=True, verbose_name='Has SEM'),
        ),
        migrations.AlterField(
            model_name='semestersubject',
            name='has_tw',
            field=models.BooleanField(default=False, verbose_name='Has TW'),
        ),
        migrations.AlterField(
            model_name='semestersubject',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='semestersubject',
            name='semester',
            field=models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2'), ('3', 'Semester 3'), ('4', 'Semester 4'), ('5', 'Semester 5'), ('6', 'Semester 6'), ('7', 'Semester 7'), ('8', 'Semester 8')], max_length=1),
        ),
        migrations.AlterField(
            model_name='semestersubject',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_subjects', to='core.studentclass', verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='semestersubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_subjects', to='core.subject', verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='semestersummary',
            name='cgpa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='semestersummary',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='academic_year',
            field=models.CharField(help_text='e.g. 2024-25', max_length=10, verbose_name='Academic Year'),
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='section',
            field=models.CharField(help_text='e.g. A, B, C', max_length=5, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Subject Code'),
        ),
        migrations.AlterField(
            model_name='subjectcombination',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_combinations', to='core.studentclass'),
        ),
        migrations.AlterField(
            model_name='subjectcombination',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_combinations', to='core.subject'),
        ),
    ]
