# Generated by Django 5.2.12 on 2026-03-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_teacher_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestersubject',
            name='min_ia1',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='semestersubject',
            name='min_ia2',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='semestersubject',
            name='min_oral',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='semestersubject',
            name='min_sem',
            field=models.PositiveSmallIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='semestersubject',
            name='min_tw',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
